apiVersion: batch/v1
kind: Job
metadata:
  name: seed-data
spec:
  template:
    spec:
      containers:
        - name: seed-data
          image: seed-data:latest
          imagePullPolicy: Never
      restartPolicy: Never
  backoffLimit: 4
